/********************************************************************
* src/GsimRunDataDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/GsimRunDataDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableGsimRunDataDict();
extern void G__cpp_setup_inheritanceGsimRunDataDict();
extern void G__cpp_setup_typetableGsimRunDataDict();
extern void G__cpp_setup_memvarGsimRunDataDict();
extern void G__cpp_setup_globalGsimRunDataDict();
extern void G__cpp_setup_memfuncGsimRunDataDict();
extern void G__cpp_setup_funcGsimRunDataDict();
extern void G__set_cpp_environmentGsimRunDataDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "./GsimData/GsimRunData.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__GsimRunDataDictLN_TClass;
extern G__linked_taginfo G__GsimRunDataDictLN_TBuffer;
extern G__linked_taginfo G__GsimRunDataDictLN_TMemberInspector;
extern G__linked_taginfo G__GsimRunDataDictLN_TObject;
extern G__linked_taginfo G__GsimRunDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__GsimRunDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GsimRunDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__GsimRunDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GsimRunDataDictLN_GsimRunData;

/* STUB derived class for protected member access */
