/********************************************************************
* src/GsimRandDataDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/GsimRandDataDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableGsimRandDataDict();
extern void G__cpp_setup_inheritanceGsimRandDataDict();
extern void G__cpp_setup_typetableGsimRandDataDict();
extern void G__cpp_setup_memvarGsimRandDataDict();
extern void G__cpp_setup_globalGsimRandDataDict();
extern void G__cpp_setup_memfuncGsimRandDataDict();
extern void G__cpp_setup_funcGsimRandDataDict();
extern void G__set_cpp_environmentGsimRandDataDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "./GsimData/GsimRandData.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__GsimRandDataDictLN_TClass;
extern G__linked_taginfo G__GsimRandDataDictLN_TBuffer;
extern G__linked_taginfo G__GsimRandDataDictLN_TMemberInspector;
extern G__linked_taginfo G__GsimRandDataDictLN_TObject;
extern G__linked_taginfo G__GsimRandDataDictLN_vectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgR;
extern G__linked_taginfo G__GsimRandDataDictLN_string;
extern G__linked_taginfo G__GsimRandDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__GsimRandDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GsimRandDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__GsimRandDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GsimRandDataDictLN_GsimRandData;

/* STUB derived class for protected member access */
