/********************************************************************
* src/GsimEventDataDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/GsimEventDataDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableGsimEventDataDict();
extern void G__cpp_setup_inheritanceGsimEventDataDict();
extern void G__cpp_setup_typetableGsimEventDataDict();
extern void G__cpp_setup_memvarGsimEventDataDict();
extern void G__cpp_setup_globalGsimEventDataDict();
extern void G__cpp_setup_memfuncGsimEventDataDict();
extern void G__cpp_setup_funcGsimEventDataDict();
extern void G__set_cpp_environmentGsimEventDataDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "./GsimData/GsimEventData.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__GsimEventDataDictLN_TClass;
extern G__linked_taginfo G__GsimEventDataDictLN_TBuffer;
extern G__linked_taginfo G__GsimEventDataDictLN_TMemberInspector;
extern G__linked_taginfo G__GsimEventDataDictLN_TObject;
extern G__linked_taginfo G__GsimEventDataDictLN_string;
extern G__linked_taginfo G__GsimEventDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__GsimEventDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GsimEventDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__GsimEventDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GsimEventDataDictLN_GsimEventData;

/* STUB derived class for protected member access */
