/********************************************************************
* src/GsimGenParticleDataDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/GsimGenParticleDataDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableGsimGenParticleDataDict();
extern void G__cpp_setup_inheritanceGsimGenParticleDataDict();
extern void G__cpp_setup_typetableGsimGenParticleDataDict();
extern void G__cpp_setup_memvarGsimGenParticleDataDict();
extern void G__cpp_setup_globalGsimGenParticleDataDict();
extern void G__cpp_setup_memfuncGsimGenParticleDataDict();
extern void G__cpp_setup_funcGsimGenParticleDataDict();
extern void G__set_cpp_environmentGsimGenParticleDataDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "./GsimData/GsimGenParticleData.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__GsimGenParticleDataDictLN_TClass;
extern G__linked_taginfo G__GsimGenParticleDataDictLN_TBuffer;
extern G__linked_taginfo G__GsimGenParticleDataDictLN_TMemberInspector;
extern G__linked_taginfo G__GsimGenParticleDataDictLN_TObject;
extern G__linked_taginfo G__GsimGenParticleDataDictLN_string;
extern G__linked_taginfo G__GsimGenParticleDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__GsimGenParticleDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GsimGenParticleDataDictLN_TClonesArray;
extern G__linked_taginfo G__GsimGenParticleDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__GsimGenParticleDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GsimGenParticleDataDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__GsimGenParticleDataDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__GsimGenParticleDataDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__GsimGenParticleDataDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__GsimGenParticleDataDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__GsimGenParticleDataDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__GsimGenParticleDataDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__GsimGenParticleDataDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__GsimGenParticleDataDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__GsimGenParticleDataDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__GsimGenParticleDataDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__GsimGenParticleDataDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__GsimGenParticleDataDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__GsimGenParticleDataDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__GsimGenParticleDataDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__GsimGenParticleDataDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__GsimGenParticleDataDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__GsimGenParticleDataDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__GsimGenParticleDataDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__GsimGenParticleDataDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__GsimGenParticleDataDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__GsimGenParticleDataDictLN_listlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__GsimGenParticleDataDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__GsimGenParticleDataDictLN_GsimGenParticleData;
extern G__linked_taginfo G__GsimGenParticleDataDictLN_listlEGsimTrackDatamUcOallocatorlEGsimTrackDatamUgRsPgR;

/* STUB derived class for protected member access */
