//
// File generated by rootcint at Sun Jun  3 02:38:15 2012

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME srcdIGsimGenParticleDataDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "GsimGenParticleDataDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void GsimGenParticleData_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_GsimGenParticleData(void *p = 0);
   static void *newArray_GsimGenParticleData(Long_t size, void *p);
   static void delete_GsimGenParticleData(void *p);
   static void deleteArray_GsimGenParticleData(void *p);
   static void destruct_GsimGenParticleData(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::GsimGenParticleData*)
   {
      ::GsimGenParticleData *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::GsimGenParticleData >(0);
      static ::ROOT::TGenericClassInfo 
         instance("GsimGenParticleData", ::GsimGenParticleData::Class_Version(), "././GsimData/GsimGenParticleData.h", 34,
                  typeid(::GsimGenParticleData), DefineBehavior(ptr, ptr),
                  &::GsimGenParticleData::Dictionary, isa_proxy, 4,
                  sizeof(::GsimGenParticleData) );
      instance.SetNew(&new_GsimGenParticleData);
      instance.SetNewArray(&newArray_GsimGenParticleData);
      instance.SetDelete(&delete_GsimGenParticleData);
      instance.SetDeleteArray(&deleteArray_GsimGenParticleData);
      instance.SetDestructor(&destruct_GsimGenParticleData);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::GsimGenParticleData*)
   {
      return GenerateInitInstanceLocal((::GsimGenParticleData*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::GsimGenParticleData*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *GsimGenParticleData::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *GsimGenParticleData::Class_Name()
{
   return "GsimGenParticleData";
}

//______________________________________________________________________________
const char *GsimGenParticleData::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::GsimGenParticleData*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int GsimGenParticleData::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::GsimGenParticleData*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void GsimGenParticleData::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::GsimGenParticleData*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *GsimGenParticleData::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::GsimGenParticleData*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void GsimGenParticleData::Streamer(TBuffer &R__b)
{
   // Stream an object of class GsimGenParticleData.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(GsimGenParticleData::Class(),this);
   } else {
      R__b.WriteClassBuffer(GsimGenParticleData::Class(),this);
   }
}

//______________________________________________________________________________
void GsimGenParticleData::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class GsimGenParticleData.
      TClass *R__cl = ::GsimGenParticleData::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*briefTracks", &briefTracks);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "version", &version);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "name", (void*)&name);
      R__insp.InspectMember("string", (void*)&name, "name.", true);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "className", (void*)&className);
      R__insp.InspectMember("string", (void*)&className, "className.", true);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_GsimGenParticleData(void *p) {
      return  p ? new(p) ::GsimGenParticleData : new ::GsimGenParticleData;
   }
   static void *newArray_GsimGenParticleData(Long_t nElements, void *p) {
      return p ? new(p) ::GsimGenParticleData[nElements] : new ::GsimGenParticleData[nElements];
   }
   // Wrapper around operator delete
   static void delete_GsimGenParticleData(void *p) {
      delete ((::GsimGenParticleData*)p);
   }
   static void deleteArray_GsimGenParticleData(void *p) {
      delete [] ((::GsimGenParticleData*)p);
   }
   static void destruct_GsimGenParticleData(void *p) {
      typedef ::GsimGenParticleData current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::GsimGenParticleData

/********************************************************
* src/GsimGenParticleDataDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableGsimGenParticleDataDict();

extern "C" void G__set_cpp_environmentGsimGenParticleDataDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("./GsimData/GsimGenParticleData.h");
  G__cpp_reset_tagtableGsimGenParticleDataDict();
}
#include <new>
extern "C" int G__cpp_dllrevGsimGenParticleDataDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* GsimGenParticleData */
static int G__GsimGenParticleDataDict_246_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   GsimGenParticleData* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new GsimGenParticleData[n];
     } else {
       p = new((void*) gvp) GsimGenParticleData[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new GsimGenParticleData;
     } else {
       p = new((void*) gvp) GsimGenParticleData;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_GsimGenParticleData));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimGenParticleDataDict_246_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GsimGenParticleData*) G__getstructoffset())->initializeDataValues();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimGenParticleDataDict_246_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         string* pobj;
         string xobj = ((GsimGenParticleData*) G__getstructoffset())->getClassName();
         pobj = new string(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimGenParticleDataDict_246_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) GsimGenParticleData::getArraySize());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimGenParticleDataDict_246_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GsimGenParticleData*) G__getstructoffset())->dump();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimGenParticleDataDict_246_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GsimGenParticleData*) G__getstructoffset())->scanParent((int) G__int(libp->para[0]), *(list<GsimTrackData*>*) libp->para[1].ref
, *(list<int>*) libp->para[2].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimGenParticleDataDict_246_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) GsimGenParticleData::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimGenParticleDataDict_246_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) GsimGenParticleData::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimGenParticleDataDict_246_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) GsimGenParticleData::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimGenParticleDataDict_246_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      GsimGenParticleData::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimGenParticleDataDict_246_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GsimGenParticleData*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimGenParticleDataDict_246_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) GsimGenParticleData::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimGenParticleDataDict_246_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) GsimGenParticleData::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimGenParticleDataDict_246_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) GsimGenParticleData::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimGenParticleDataDict_246_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) GsimGenParticleData::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__GsimGenParticleDataDict_246_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   GsimGenParticleData* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new GsimGenParticleData(*(GsimGenParticleData*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_GsimGenParticleData));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef GsimGenParticleData G__TGsimGenParticleData;
static int G__GsimGenParticleDataDict_246_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (GsimGenParticleData*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((GsimGenParticleData*) (soff+(sizeof(GsimGenParticleData)*i)))->~G__TGsimGenParticleData();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (GsimGenParticleData*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((GsimGenParticleData*) (soff))->~G__TGsimGenParticleData();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__GsimGenParticleDataDict_246_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   GsimGenParticleData* dest = (GsimGenParticleData*) G__getstructoffset();
   *dest = *(GsimGenParticleData*) libp->para[0].ref;
   const GsimGenParticleData& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* GsimGenParticleData */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncGsimGenParticleDataDict {
 public:
  G__Sizep2memfuncGsimGenParticleDataDict(): p(&G__Sizep2memfuncGsimGenParticleDataDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncGsimGenParticleDataDict::*p)();
};

size_t G__get_sizep2memfuncGsimGenParticleDataDict()
{
  G__Sizep2memfuncGsimGenParticleDataDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceGsimGenParticleDataDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_GsimGenParticleData))) {
     GsimGenParticleData *G__Lderived;
     G__Lderived=(GsimGenParticleData*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_GsimGenParticleData),G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableGsimGenParticleDataDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("list<GsimTrackData*>",117,G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_listlEGsimTrackDatamUcOallocatorlEGsimTrackDatamUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* GsimGenParticleData */
static void G__setup_memvarGsimGenParticleData(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_GsimGenParticleData));
   { GsimGenParticleData *p; p=(GsimGenParticleData*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->briefTracks)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_TClonesArray),-1,-1,1,"briefTracks=",0,"->");
   G__memvar_setup((void*)((long)(&p->version)-(long)(p)),114,0,0,-1,G__defined_typename("UShort_t"),-1,1,"version=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_string),-1,-1,2,"name=",0,"!");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_string),-1,-1,2,"className=",0,"!");
   G__memvar_setup((void*)G__PVOID,105,0,1,-1,-1,-2,2,"s_arraySize=0LL",0,"!");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarGsimGenParticleDataDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncGsimGenParticleData(void) {
   /* GsimGenParticleData */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_GsimGenParticleData));
   G__memfunc_setup("GsimGenParticleData",1880,G__GsimGenParticleDataDict_246_0_1, 105, G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_GsimGenParticleData), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Clear",487,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "C - 'Option_t' 10 '\"\"' opt", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("initializeDataValues",2076,G__GsimGenParticleDataDict_246_0_3, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getClassName",1207,G__GsimGenParticleDataDict_246_0_4, 117, G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_string), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getArraySize",1242,G__GsimGenParticleDataDict_246_0_5, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&GsimGenParticleData::getArraySize) ), 0);
   G__memfunc_setup("dump",438,G__GsimGenParticleDataDict_246_0_6, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("scanParent",1039,G__GsimGenParticleDataDict_246_0_7, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - iParent u 'list<GsimTrackData*,allocator<GsimTrackData*> >' 'list<GsimTrackData*>' 1 - tdp "
"u 'list<int,allocator<int> >' 'list<int>' 1 - state", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__GsimGenParticleDataDict_246_0_8, 85, G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&GsimGenParticleData::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__GsimGenParticleDataDict_246_0_9, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&GsimGenParticleData::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__GsimGenParticleDataDict_246_0_10, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&GsimGenParticleData::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__GsimGenParticleDataDict_246_0_11, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&GsimGenParticleData::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - insp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__GsimGenParticleDataDict_246_0_15, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__GsimGenParticleDataDict_246_0_16, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&GsimGenParticleData::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__GsimGenParticleDataDict_246_0_17, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&GsimGenParticleData::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__GsimGenParticleDataDict_246_0_18, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&GsimGenParticleData::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__GsimGenParticleDataDict_246_0_19, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&GsimGenParticleData::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("GsimGenParticleData", 1880, G__GsimGenParticleDataDict_246_0_20, (int) ('i'), G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_GsimGenParticleData), -1, 0, 1, 1, 1, 0, "u 'GsimGenParticleData' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~GsimGenParticleData", 2006, G__GsimGenParticleDataDict_246_0_21, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__GsimGenParticleDataDict_246_0_22, (int) ('u'), G__get_linked_tagnum(&G__GsimGenParticleDataDictLN_GsimGenParticleData), -1, 1, 1, 1, 1, 0, "u 'GsimGenParticleData' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncGsimGenParticleDataDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalGsimGenParticleDataDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcGsimGenParticleDataDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__GsimGenParticleDataDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__GsimGenParticleDataDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__GsimGenParticleDataDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__GsimGenParticleDataDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__GsimGenParticleDataDictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__GsimGenParticleDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__GsimGenParticleDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__GsimGenParticleDataDictLN_TClonesArray = { "TClonesArray" , 99 , -1 };
G__linked_taginfo G__GsimGenParticleDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__GsimGenParticleDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__GsimGenParticleDataDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__GsimGenParticleDataDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__GsimGenParticleDataDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__GsimGenParticleDataDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__GsimGenParticleDataDictLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__GsimGenParticleDataDictLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__GsimGenParticleDataDictLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__GsimGenParticleDataDictLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__GsimGenParticleDataDictLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__GsimGenParticleDataDictLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__GsimGenParticleDataDictLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__GsimGenParticleDataDictLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__GsimGenParticleDataDictLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__GsimGenParticleDataDictLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__GsimGenParticleDataDictLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__GsimGenParticleDataDictLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__GsimGenParticleDataDictLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__GsimGenParticleDataDictLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__GsimGenParticleDataDictLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__GsimGenParticleDataDictLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__GsimGenParticleDataDictLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__GsimGenParticleDataDictLN_listlEintcOallocatorlEintgRsPgR = { "list<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__GsimGenParticleDataDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__GsimGenParticleDataDictLN_GsimGenParticleData = { "GsimGenParticleData" , 99 , -1 };
G__linked_taginfo G__GsimGenParticleDataDictLN_listlEGsimTrackDatamUcOallocatorlEGsimTrackDatamUgRsPgR = { "list<GsimTrackData*,allocator<GsimTrackData*> >" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableGsimGenParticleDataDict() {
  G__GsimGenParticleDataDictLN_TClass.tagnum = -1 ;
  G__GsimGenParticleDataDictLN_TBuffer.tagnum = -1 ;
  G__GsimGenParticleDataDictLN_TMemberInspector.tagnum = -1 ;
  G__GsimGenParticleDataDictLN_TObject.tagnum = -1 ;
  G__GsimGenParticleDataDictLN_string.tagnum = -1 ;
  G__GsimGenParticleDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__GsimGenParticleDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GsimGenParticleDataDictLN_TClonesArray.tagnum = -1 ;
  G__GsimGenParticleDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__GsimGenParticleDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GsimGenParticleDataDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__GsimGenParticleDataDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__GsimGenParticleDataDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__GsimGenParticleDataDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__GsimGenParticleDataDictLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__GsimGenParticleDataDictLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__GsimGenParticleDataDictLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__GsimGenParticleDataDictLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__GsimGenParticleDataDictLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__GsimGenParticleDataDictLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__GsimGenParticleDataDictLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__GsimGenParticleDataDictLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__GsimGenParticleDataDictLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__GsimGenParticleDataDictLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__GsimGenParticleDataDictLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__GsimGenParticleDataDictLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__GsimGenParticleDataDictLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__GsimGenParticleDataDictLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__GsimGenParticleDataDictLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__GsimGenParticleDataDictLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__GsimGenParticleDataDictLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__GsimGenParticleDataDictLN_listlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__GsimGenParticleDataDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__GsimGenParticleDataDictLN_GsimGenParticleData.tagnum = -1 ;
  G__GsimGenParticleDataDictLN_listlEGsimTrackDatamUcOallocatorlEGsimTrackDatamUgRsPgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableGsimGenParticleDataDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__GsimGenParticleDataDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__GsimGenParticleDataDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__GsimGenParticleDataDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__GsimGenParticleDataDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__GsimGenParticleDataDictLN_string);
   G__get_linked_tagnum_fwd(&G__GsimGenParticleDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__GsimGenParticleDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__GsimGenParticleDataDictLN_TClonesArray);
   G__get_linked_tagnum_fwd(&G__GsimGenParticleDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__GsimGenParticleDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__GsimGenParticleDataDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__GsimGenParticleDataDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__GsimGenParticleDataDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GsimGenParticleDataDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__GsimGenParticleDataDictLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GsimGenParticleDataDictLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GsimGenParticleDataDictLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GsimGenParticleDataDictLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GsimGenParticleDataDictLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GsimGenParticleDataDictLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GsimGenParticleDataDictLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GsimGenParticleDataDictLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GsimGenParticleDataDictLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GsimGenParticleDataDictLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GsimGenParticleDataDictLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GsimGenParticleDataDictLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GsimGenParticleDataDictLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__GsimGenParticleDataDictLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GsimGenParticleDataDictLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__GsimGenParticleDataDictLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GsimGenParticleDataDictLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__GsimGenParticleDataDictLN_listlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__GsimGenParticleDataDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__GsimGenParticleDataDictLN_GsimGenParticleData),sizeof(GsimGenParticleData),-1,292096,(char*)NULL,G__setup_memvarGsimGenParticleData,G__setup_memfuncGsimGenParticleData);
   G__get_linked_tagnum_fwd(&G__GsimGenParticleDataDictLN_listlEGsimTrackDatamUcOallocatorlEGsimTrackDatamUgRsPgR);
}
extern "C" void G__cpp_setupGsimGenParticleDataDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupGsimGenParticleDataDict()");
  G__set_cpp_environmentGsimGenParticleDataDict();
  G__cpp_setup_tagtableGsimGenParticleDataDict();

  G__cpp_setup_inheritanceGsimGenParticleDataDict();

  G__cpp_setup_typetableGsimGenParticleDataDict();

  G__cpp_setup_memvarGsimGenParticleDataDict();

  G__cpp_setup_memfuncGsimGenParticleDataDict();
  G__cpp_setup_globalGsimGenParticleDataDict();
  G__cpp_setup_funcGsimGenParticleDataDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncGsimGenParticleDataDict();
  return;
}
class G__cpp_setup_initGsimGenParticleDataDict {
  public:
    G__cpp_setup_initGsimGenParticleDataDict() { G__add_setup_func("GsimGenParticleDataDict",(G__incsetup)(&G__cpp_setupGsimGenParticleDataDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initGsimGenParticleDataDict() { G__remove_setup_func("GsimGenParticleDataDict"); }
};
G__cpp_setup_initGsimGenParticleDataDict G__cpp_setup_initializerGsimGenParticleDataDict;

