//
// File generated by rootcint at Sun Jun  3 02:38:15 2012

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME srcdIGsimEventDataDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "GsimEventDataDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void GsimEventData_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_GsimEventData(void *p = 0);
   static void *newArray_GsimEventData(Long_t size, void *p);
   static void delete_GsimEventData(void *p);
   static void deleteArray_GsimEventData(void *p);
   static void destruct_GsimEventData(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::GsimEventData*)
   {
      ::GsimEventData *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::GsimEventData >(0);
      static ::ROOT::TGenericClassInfo 
         instance("GsimEventData", ::GsimEventData::Class_Version(), "././GsimData/GsimEventData.h", 41,
                  typeid(::GsimEventData), DefineBehavior(ptr, ptr),
                  &::GsimEventData::Dictionary, isa_proxy, 4,
                  sizeof(::GsimEventData) );
      instance.SetNew(&new_GsimEventData);
      instance.SetNewArray(&newArray_GsimEventData);
      instance.SetDelete(&delete_GsimEventData);
      instance.SetDeleteArray(&deleteArray_GsimEventData);
      instance.SetDestructor(&destruct_GsimEventData);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::GsimEventData*)
   {
      return GenerateInitInstanceLocal((::GsimEventData*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::GsimEventData*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *GsimEventData::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *GsimEventData::Class_Name()
{
   return "GsimEventData";
}

//______________________________________________________________________________
const char *GsimEventData::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::GsimEventData*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int GsimEventData::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::GsimEventData*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void GsimEventData::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::GsimEventData*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *GsimEventData::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::GsimEventData*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void GsimEventData::Streamer(TBuffer &R__b)
{
   // Stream an object of class GsimEventData.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(GsimEventData::Class(),this);
   } else {
      R__b.WriteClassBuffer(GsimEventData::Class(),this);
   }
}

//______________________________________________________________________________
void GsimEventData::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class GsimEventData.
      TClass *R__cl = ::GsimEventData::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "expMC", &expMC);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "run_number", &run_number);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "spill_number", &spill_number);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "event_number", &event_number);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "trigger", &trigger);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "time_stamp", &time_stamp);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "status", &status);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "version", &version);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "name", (void*)&name);
      R__insp.InspectMember("string", (void*)&name, "name.", true);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "className", (void*)&className);
      R__insp.InspectMember("string", (void*)&className, "className.", true);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_GsimEventData(void *p) {
      return  p ? new(p) ::GsimEventData : new ::GsimEventData;
   }
   static void *newArray_GsimEventData(Long_t nElements, void *p) {
      return p ? new(p) ::GsimEventData[nElements] : new ::GsimEventData[nElements];
   }
   // Wrapper around operator delete
   static void delete_GsimEventData(void *p) {
      delete ((::GsimEventData*)p);
   }
   static void deleteArray_GsimEventData(void *p) {
      delete [] ((::GsimEventData*)p);
   }
   static void destruct_GsimEventData(void *p) {
      typedef ::GsimEventData current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::GsimEventData

/********************************************************
* src/GsimEventDataDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableGsimEventDataDict();

extern "C" void G__set_cpp_environmentGsimEventDataDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("./GsimData/GsimEventData.h");
  G__cpp_reset_tagtableGsimEventDataDict();
}
#include <new>
extern "C" int G__cpp_dllrevGsimEventDataDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* GsimEventData */
static int G__GsimEventDataDict_162_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   GsimEventData* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new GsimEventData[n];
     } else {
       p = new((void*) gvp) GsimEventData[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new GsimEventData;
     } else {
       p = new((void*) gvp) GsimEventData;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__GsimEventDataDictLN_GsimEventData));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimEventDataDict_162_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GsimEventData*) G__getstructoffset())->initializeDataValues();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimEventDataDict_162_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         string* pobj;
         string xobj = ((GsimEventData*) G__getstructoffset())->getClassName();
         pobj = new string(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimEventDataDict_162_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) GsimEventData::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimEventDataDict_162_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) GsimEventData::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimEventDataDict_162_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) GsimEventData::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimEventDataDict_162_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      GsimEventData::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimEventDataDict_162_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GsimEventData*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimEventDataDict_162_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) GsimEventData::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimEventDataDict_162_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) GsimEventData::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimEventDataDict_162_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) GsimEventData::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimEventDataDict_162_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) GsimEventData::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__GsimEventDataDict_162_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   GsimEventData* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new GsimEventData(*(GsimEventData*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__GsimEventDataDictLN_GsimEventData));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef GsimEventData G__TGsimEventData;
static int G__GsimEventDataDict_162_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (GsimEventData*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((GsimEventData*) (soff+(sizeof(GsimEventData)*i)))->~G__TGsimEventData();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (GsimEventData*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((GsimEventData*) (soff))->~G__TGsimEventData();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__GsimEventDataDict_162_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   GsimEventData* dest = (GsimEventData*) G__getstructoffset();
   *dest = *(GsimEventData*) libp->para[0].ref;
   const GsimEventData& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* GsimEventData */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncGsimEventDataDict {
 public:
  G__Sizep2memfuncGsimEventDataDict(): p(&G__Sizep2memfuncGsimEventDataDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncGsimEventDataDict::*p)();
};

size_t G__get_sizep2memfuncGsimEventDataDict()
{
  G__Sizep2memfuncGsimEventDataDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceGsimEventDataDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__GsimEventDataDictLN_GsimEventData))) {
     GsimEventData *G__Lderived;
     G__Lderived=(GsimEventData*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__GsimEventDataDictLN_GsimEventData),G__get_linked_tagnum(&G__GsimEventDataDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableGsimEventDataDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__GsimEventDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GsimEventDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GsimEventDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GsimEventDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GsimEventDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__GsimEventDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GsimEventDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GsimEventDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GsimEventDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GsimEventDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* GsimEventData */
static void G__setup_memvarGsimEventData(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__GsimEventDataDictLN_GsimEventData));
   { GsimEventData *p; p=(GsimEventData*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->expMC)-(long)(p)),114,0,0,-1,G__defined_typename("UShort_t"),-1,1,"expMC=",0,"exp=1,MC=2");
   G__memvar_setup((void*)((long)(&p->run_number)-(long)(p)),114,0,0,-1,G__defined_typename("UShort_t"),-1,1,"run_number=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->spill_number)-(long)(p)),114,0,0,-1,G__defined_typename("UShort_t"),-1,1,"spill_number=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->event_number)-(long)(p)),104,0,0,-1,G__defined_typename("UInt_t"),-1,1,"event_number=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->trigger)-(long)(p)),104,0,0,-1,G__defined_typename("UInt_t"),-1,1,"trigger=",0,"trigger bit pattern");
   G__memvar_setup((void*)((long)(&p->time_stamp)-(long)(p)),104,0,0,-1,G__defined_typename("UInt_t"),-1,1,"time_stamp=",0,"localtime");
   G__memvar_setup((void*)((long)(&p->status)-(long)(p)),104,0,0,-1,G__defined_typename("UInt_t"),-1,1,"status=",0,"general status");
   G__memvar_setup((void*)((long)(&p->version)-(long)(p)),114,0,0,-1,G__defined_typename("UShort_t"),-1,1,"version=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__GsimEventDataDictLN_string),-1,-1,2,"name=",0,"!");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__GsimEventDataDictLN_string),-1,-1,2,"className=",0,"!");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GsimEventDataDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarGsimEventDataDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncGsimEventData(void) {
   /* GsimEventData */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__GsimEventDataDictLN_GsimEventData));
   G__memfunc_setup("GsimEventData",1292,G__GsimEventDataDict_162_0_1, 105, G__get_linked_tagnum(&G__GsimEventDataDictLN_GsimEventData), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Clear",487,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "C - 'Option_t' 10 '\"\"' opt", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("initializeDataValues",2076,G__GsimEventDataDict_162_0_3, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getClassName",1207,G__GsimEventDataDict_162_0_4, 117, G__get_linked_tagnum(&G__GsimEventDataDictLN_string), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__GsimEventDataDict_162_0_5, 85, G__get_linked_tagnum(&G__GsimEventDataDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&GsimEventData::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__GsimEventDataDict_162_0_6, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&GsimEventData::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__GsimEventDataDict_162_0_7, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&GsimEventData::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__GsimEventDataDict_162_0_8, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&GsimEventData::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__GsimEventDataDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - insp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__GsimEventDataDict_162_0_12, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__GsimEventDataDict_162_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&GsimEventData::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__GsimEventDataDict_162_0_14, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&GsimEventData::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__GsimEventDataDict_162_0_15, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&GsimEventData::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__GsimEventDataDict_162_0_16, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&GsimEventData::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("GsimEventData", 1292, G__GsimEventDataDict_162_0_17, (int) ('i'), G__get_linked_tagnum(&G__GsimEventDataDictLN_GsimEventData), -1, 0, 1, 1, 1, 0, "u 'GsimEventData' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~GsimEventData", 1418, G__GsimEventDataDict_162_0_18, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__GsimEventDataDict_162_0_19, (int) ('u'), G__get_linked_tagnum(&G__GsimEventDataDictLN_GsimEventData), -1, 1, 1, 1, 1, 0, "u 'GsimEventData' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncGsimEventDataDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalGsimEventDataDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcGsimEventDataDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__GsimEventDataDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__GsimEventDataDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__GsimEventDataDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__GsimEventDataDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__GsimEventDataDictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__GsimEventDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__GsimEventDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__GsimEventDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__GsimEventDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__GsimEventDataDictLN_GsimEventData = { "GsimEventData" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableGsimEventDataDict() {
  G__GsimEventDataDictLN_TClass.tagnum = -1 ;
  G__GsimEventDataDictLN_TBuffer.tagnum = -1 ;
  G__GsimEventDataDictLN_TMemberInspector.tagnum = -1 ;
  G__GsimEventDataDictLN_TObject.tagnum = -1 ;
  G__GsimEventDataDictLN_string.tagnum = -1 ;
  G__GsimEventDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__GsimEventDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GsimEventDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__GsimEventDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GsimEventDataDictLN_GsimEventData.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableGsimEventDataDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__GsimEventDataDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__GsimEventDataDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__GsimEventDataDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__GsimEventDataDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__GsimEventDataDictLN_string);
   G__get_linked_tagnum_fwd(&G__GsimEventDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__GsimEventDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__GsimEventDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__GsimEventDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__GsimEventDataDictLN_GsimEventData),sizeof(GsimEventData),-1,292096,(char*)NULL,G__setup_memvarGsimEventData,G__setup_memfuncGsimEventData);
}
extern "C" void G__cpp_setupGsimEventDataDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupGsimEventDataDict()");
  G__set_cpp_environmentGsimEventDataDict();
  G__cpp_setup_tagtableGsimEventDataDict();

  G__cpp_setup_inheritanceGsimEventDataDict();

  G__cpp_setup_typetableGsimEventDataDict();

  G__cpp_setup_memvarGsimEventDataDict();

  G__cpp_setup_memfuncGsimEventDataDict();
  G__cpp_setup_globalGsimEventDataDict();
  G__cpp_setup_funcGsimEventDataDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncGsimEventDataDict();
  return;
}
class G__cpp_setup_initGsimEventDataDict {
  public:
    G__cpp_setup_initGsimEventDataDict() { G__add_setup_func("GsimEventDataDict",(G__incsetup)(&G__cpp_setupGsimEventDataDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initGsimEventDataDict() { G__remove_setup_func("GsimEventDataDict"); }
};
G__cpp_setup_initGsimEventDataDict G__cpp_setup_initializerGsimEventDataDict;

