/********************************************************************
* src/GsimDetectorDataDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/GsimDetectorDataDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableGsimDetectorDataDict();
extern void G__cpp_setup_inheritanceGsimDetectorDataDict();
extern void G__cpp_setup_typetableGsimDetectorDataDict();
extern void G__cpp_setup_memvarGsimDetectorDataDict();
extern void G__cpp_setup_globalGsimDetectorDataDict();
extern void G__cpp_setup_memfuncGsimDetectorDataDict();
extern void G__cpp_setup_funcGsimDetectorDataDict();
extern void G__set_cpp_environmentGsimDetectorDataDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "./GsimData/GsimDetectorData.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__GsimDetectorDataDictLN_TClass;
extern G__linked_taginfo G__GsimDetectorDataDictLN_TBuffer;
extern G__linked_taginfo G__GsimDetectorDataDictLN_TMemberInspector;
extern G__linked_taginfo G__GsimDetectorDataDictLN_TObject;
extern G__linked_taginfo G__GsimDetectorDataDictLN_TString;
extern G__linked_taginfo G__GsimDetectorDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__GsimDetectorDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GsimDetectorDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__GsimDetectorDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GsimDetectorDataDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__GsimDetectorDataDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__GsimDetectorDataDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__GsimDetectorDataDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__GsimDetectorDataDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__GsimDetectorDataDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__GsimDetectorDataDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__GsimDetectorDataDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__GsimDetectorDataDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__GsimDetectorDataDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__GsimDetectorDataDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__GsimDetectorDataDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__GsimDetectorDataDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__GsimDetectorDataDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__GsimDetectorDataDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__GsimDetectorDataDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__GsimDetectorDataDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__GsimDetectorDataDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__GsimDetectorDataDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__GsimDetectorDataDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__GsimDetectorDataDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__GsimDetectorDataDictLN_TVector3;
extern G__linked_taginfo G__GsimDetectorDataDictLN_GsimDetectorData;
extern G__linked_taginfo G__GsimDetectorDataDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__GsimDetectorDataDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
