/********************************************************************
* src/GsimProcessDataDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/GsimProcessDataDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableGsimProcessDataDict();
extern void G__cpp_setup_inheritanceGsimProcessDataDict();
extern void G__cpp_setup_typetableGsimProcessDataDict();
extern void G__cpp_setup_memvarGsimProcessDataDict();
extern void G__cpp_setup_globalGsimProcessDataDict();
extern void G__cpp_setup_memfuncGsimProcessDataDict();
extern void G__cpp_setup_funcGsimProcessDataDict();
extern void G__set_cpp_environmentGsimProcessDataDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "./GsimData/GsimProcessData.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__GsimProcessDataDictLN_TClass;
extern G__linked_taginfo G__GsimProcessDataDictLN_TBuffer;
extern G__linked_taginfo G__GsimProcessDataDictLN_TMemberInspector;
extern G__linked_taginfo G__GsimProcessDataDictLN_TObject;
extern G__linked_taginfo G__GsimProcessDataDictLN_TString;
extern G__linked_taginfo G__GsimProcessDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__GsimProcessDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GsimProcessDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__GsimProcessDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GsimProcessDataDictLN_GsimProcessData;

/* STUB derived class for protected member access */
