//
// File generated by rootcint at Sun Jun  3 02:38:14 2012

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME srcdIGsimDetectorEventDataDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "GsimDetectorEventDataDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void GsimDetectorEventData_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_GsimDetectorEventData(void *p = 0);
   static void *newArray_GsimDetectorEventData(Long_t size, void *p);
   static void delete_GsimDetectorEventData(void *p);
   static void deleteArray_GsimDetectorEventData(void *p);
   static void destruct_GsimDetectorEventData(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::GsimDetectorEventData*)
   {
      ::GsimDetectorEventData *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::GsimDetectorEventData >(0);
      static ::ROOT::TGenericClassInfo 
         instance("GsimDetectorEventData", ::GsimDetectorEventData::Class_Version(), "././GsimData/GsimDetectorEventData.h", 76,
                  typeid(::GsimDetectorEventData), DefineBehavior(ptr, ptr),
                  &::GsimDetectorEventData::Dictionary, isa_proxy, 4,
                  sizeof(::GsimDetectorEventData) );
      instance.SetNew(&new_GsimDetectorEventData);
      instance.SetNewArray(&newArray_GsimDetectorEventData);
      instance.SetDelete(&delete_GsimDetectorEventData);
      instance.SetDeleteArray(&deleteArray_GsimDetectorEventData);
      instance.SetDestructor(&destruct_GsimDetectorEventData);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::GsimDetectorEventData*)
   {
      return GenerateInitInstanceLocal((::GsimDetectorEventData*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::GsimDetectorEventData*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *GsimDetectorEventData::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *GsimDetectorEventData::Class_Name()
{
   return "GsimDetectorEventData";
}

//______________________________________________________________________________
const char *GsimDetectorEventData::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::GsimDetectorEventData*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int GsimDetectorEventData::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::GsimDetectorEventData*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void GsimDetectorEventData::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::GsimDetectorEventData*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *GsimDetectorEventData::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::GsimDetectorEventData*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void GsimDetectorEventData::Streamer(TBuffer &R__b)
{
   // Stream an object of class GsimDetectorEventData.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(GsimDetectorEventData::Class(),this);
   } else {
      R__b.WriteClassBuffer(GsimDetectorEventData::Class(),this);
   }
}

//______________________________________________________________________________
void GsimDetectorEventData::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class GsimDetectorEventData.
      TClass *R__cl = ::GsimDetectorEventData::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "status", &status);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nHit", &nHit);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nDigi", &nDigi);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nTrig", &nTrig);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "totalEnergy", &totalEnergy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "firstHitTime", &firstHitTime);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "lastHitTime", &lastHitTime);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hits", &hits);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*digi", &digi);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*mtime", &mtime);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*trig", &trig);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "name", (void*)&name);
      R__insp.InspectMember("string", (void*)&name, "name.", true);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "className", (void*)&className);
      R__insp.InspectMember("string", (void*)&className, "className.", true);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "t1", &t1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "t2", &t2);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_GsimDetectorEventData(void *p) {
      return  p ? new(p) ::GsimDetectorEventData : new ::GsimDetectorEventData;
   }
   static void *newArray_GsimDetectorEventData(Long_t nElements, void *p) {
      return p ? new(p) ::GsimDetectorEventData[nElements] : new ::GsimDetectorEventData[nElements];
   }
   // Wrapper around operator delete
   static void delete_GsimDetectorEventData(void *p) {
      delete ((::GsimDetectorEventData*)p);
   }
   static void deleteArray_GsimDetectorEventData(void *p) {
      delete [] ((::GsimDetectorEventData*)p);
   }
   static void destruct_GsimDetectorEventData(void *p) {
      typedef ::GsimDetectorEventData current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::GsimDetectorEventData

/********************************************************
* src/GsimDetectorEventDataDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableGsimDetectorEventDataDict();

extern "C" void G__set_cpp_environmentGsimDetectorEventDataDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("./GsimData/GsimDetectorEventData.h");
  G__cpp_reset_tagtableGsimDetectorEventDataDict();
}
#include <new>
extern "C" int G__cpp_dllrevGsimDetectorEventDataDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* GsimDetectorEventData */
static int G__GsimDetectorEventDataDict_225_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   GsimDetectorEventData* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new GsimDetectorEventData[n];
     } else {
       p = new((void*) gvp) GsimDetectorEventData[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new GsimDetectorEventData;
     } else {
       p = new((void*) gvp) GsimDetectorEventData;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_GsimDetectorEventData));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimDetectorEventDataDict_225_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GsimDetectorEventData*) G__getstructoffset())->initializeDataValues();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimDetectorEventDataDict_225_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GsimDetectorEventData*) G__getstructoffset())->clearHitData();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimDetectorEventDataDict_225_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         string* pobj;
         string xobj = ((GsimDetectorEventData*) G__getstructoffset())->getClassName();
         pobj = new string(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimDetectorEventDataDict_225_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) GsimDetectorEventData::getArraySize());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimDetectorEventDataDict_225_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GsimDetectorEventData*) G__getstructoffset())->dumpHits();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimDetectorEventDataDict_225_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GsimDetectorEventData*) G__getstructoffset())->dumpDigi();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimDetectorEventDataDict_225_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) GsimDetectorEventData::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimDetectorEventDataDict_225_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) GsimDetectorEventData::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimDetectorEventDataDict_225_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) GsimDetectorEventData::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimDetectorEventDataDict_225_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      GsimDetectorEventData::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimDetectorEventDataDict_225_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GsimDetectorEventData*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimDetectorEventDataDict_225_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) GsimDetectorEventData::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimDetectorEventDataDict_225_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) GsimDetectorEventData::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimDetectorEventDataDict_225_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) GsimDetectorEventData::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimDetectorEventDataDict_225_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) GsimDetectorEventData::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__GsimDetectorEventDataDict_225_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   GsimDetectorEventData* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new GsimDetectorEventData(*(GsimDetectorEventData*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_GsimDetectorEventData));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef GsimDetectorEventData G__TGsimDetectorEventData;
static int G__GsimDetectorEventDataDict_225_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (GsimDetectorEventData*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((GsimDetectorEventData*) (soff+(sizeof(GsimDetectorEventData)*i)))->~G__TGsimDetectorEventData();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (GsimDetectorEventData*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((GsimDetectorEventData*) (soff))->~G__TGsimDetectorEventData();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__GsimDetectorEventDataDict_225_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   GsimDetectorEventData* dest = (GsimDetectorEventData*) G__getstructoffset();
   *dest = *(GsimDetectorEventData*) libp->para[0].ref;
   const GsimDetectorEventData& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* GsimDetectorEventData */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncGsimDetectorEventDataDict {
 public:
  G__Sizep2memfuncGsimDetectorEventDataDict(): p(&G__Sizep2memfuncGsimDetectorEventDataDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncGsimDetectorEventDataDict::*p)();
};

size_t G__get_sizep2memfuncGsimDetectorEventDataDict()
{
  G__Sizep2memfuncGsimDetectorEventDataDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceGsimDetectorEventDataDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_GsimDetectorEventData))) {
     GsimDetectorEventData *G__Lderived;
     G__Lderived=(GsimDetectorEventData*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_GsimDetectorEventData),G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableGsimDetectorEventDataDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* GsimDetectorEventData */
static void G__setup_memvarGsimDetectorEventData(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_GsimDetectorEventData));
   { GsimDetectorEventData *p; p=(GsimDetectorEventData*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->status)-(long)(p)),114,0,0,-1,G__defined_typename("UShort_t"),-1,1,"status=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nHit)-(long)(p)),114,0,0,-1,G__defined_typename("UShort_t"),-1,1,"nHit=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nDigi)-(long)(p)),114,0,0,-1,G__defined_typename("UShort_t"),-1,1,"nDigi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nTrig)-(long)(p)),114,0,0,-1,G__defined_typename("UShort_t"),-1,1,"nTrig=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->totalEnergy)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"totalEnergy=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->firstHitTime)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"firstHitTime=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->lastHitTime)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"lastHitTime=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hits)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_TClonesArray),-1,-1,1,"hits=",0,"->");
   G__memvar_setup((void*)((long)(&p->digi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_TClonesArray),-1,-1,1,"digi=",0,"->");
   G__memvar_setup((void*)((long)(&p->mtime)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_TClonesArray),-1,-1,1,"mtime=",0,"->");
   G__memvar_setup((void*)((long)(&p->trig)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_TClonesArray),-1,-1,1,"trig=",0,"->");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_string),-1,-1,2,"name=",0,"!");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_string),-1,-1,2,"className=",0,"!");
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,2,"t1=",0,"!");
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,2,"t2=",0,"!");
   G__memvar_setup((void*)G__PVOID,105,0,1,-1,-1,-2,2,"s_arraySize=0LL",0,"!");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarGsimDetectorEventDataDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncGsimDetectorEventData(void) {
   /* GsimDetectorEventData */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_GsimDetectorEventData));
   G__memfunc_setup("GsimDetectorEventData",2118,G__GsimDetectorEventDataDict_225_0_1, 105, G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_GsimDetectorEventData), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Clear",487,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "C - 'Option_t' 10 '\"\"' opt", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("initializeDataValues",2076,G__GsimDetectorEventDataDict_225_0_3, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("clearHitData",1190,G__GsimDetectorEventDataDict_225_0_4, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getClassName",1207,G__GsimDetectorEventDataDict_225_0_5, 117, G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_string), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getArraySize",1242,G__GsimDetectorEventDataDict_225_0_6, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&GsimDetectorEventData::getArraySize) ), 0);
   G__memfunc_setup("dumpHits",846,G__GsimDetectorEventDataDict_225_0_7, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("dumpDigi",819,G__GsimDetectorEventDataDict_225_0_8, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__GsimDetectorEventDataDict_225_0_9, 85, G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&GsimDetectorEventData::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__GsimDetectorEventDataDict_225_0_10, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&GsimDetectorEventData::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__GsimDetectorEventDataDict_225_0_11, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&GsimDetectorEventData::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__GsimDetectorEventDataDict_225_0_12, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&GsimDetectorEventData::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - insp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__GsimDetectorEventDataDict_225_0_16, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__GsimDetectorEventDataDict_225_0_17, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&GsimDetectorEventData::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__GsimDetectorEventDataDict_225_0_18, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&GsimDetectorEventData::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__GsimDetectorEventDataDict_225_0_19, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&GsimDetectorEventData::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__GsimDetectorEventDataDict_225_0_20, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&GsimDetectorEventData::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("GsimDetectorEventData", 2118, G__GsimDetectorEventDataDict_225_0_21, (int) ('i'), 
G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_GsimDetectorEventData), -1, 0, 1, 1, 1, 0, "u 'GsimDetectorEventData' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~GsimDetectorEventData", 2244, G__GsimDetectorEventDataDict_225_0_22, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__GsimDetectorEventDataDict_225_0_23, (int) ('u'), G__get_linked_tagnum(&G__GsimDetectorEventDataDictLN_GsimDetectorEventData), -1, 1, 1, 1, 1, 0, "u 'GsimDetectorEventData' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncGsimDetectorEventDataDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalGsimDetectorEventDataDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcGsimDetectorEventDataDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__GsimDetectorEventDataDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__GsimDetectorEventDataDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__GsimDetectorEventDataDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__GsimDetectorEventDataDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__GsimDetectorEventDataDictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__GsimDetectorEventDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__GsimDetectorEventDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__GsimDetectorEventDataDictLN_TClonesArray = { "TClonesArray" , 99 , -1 };
G__linked_taginfo G__GsimDetectorEventDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__GsimDetectorEventDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__GsimDetectorEventDataDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__GsimDetectorEventDataDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__GsimDetectorEventDataDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__GsimDetectorEventDataDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__GsimDetectorEventDataDictLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__GsimDetectorEventDataDictLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__GsimDetectorEventDataDictLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__GsimDetectorEventDataDictLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__GsimDetectorEventDataDictLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__GsimDetectorEventDataDictLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__GsimDetectorEventDataDictLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__GsimDetectorEventDataDictLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__GsimDetectorEventDataDictLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__GsimDetectorEventDataDictLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__GsimDetectorEventDataDictLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__GsimDetectorEventDataDictLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__GsimDetectorEventDataDictLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__GsimDetectorEventDataDictLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__GsimDetectorEventDataDictLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__GsimDetectorEventDataDictLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__GsimDetectorEventDataDictLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__GsimDetectorEventDataDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__GsimDetectorEventDataDictLN_GsimDetectorEventData = { "GsimDetectorEventData" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableGsimDetectorEventDataDict() {
  G__GsimDetectorEventDataDictLN_TClass.tagnum = -1 ;
  G__GsimDetectorEventDataDictLN_TBuffer.tagnum = -1 ;
  G__GsimDetectorEventDataDictLN_TMemberInspector.tagnum = -1 ;
  G__GsimDetectorEventDataDictLN_TObject.tagnum = -1 ;
  G__GsimDetectorEventDataDictLN_string.tagnum = -1 ;
  G__GsimDetectorEventDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__GsimDetectorEventDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GsimDetectorEventDataDictLN_TClonesArray.tagnum = -1 ;
  G__GsimDetectorEventDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__GsimDetectorEventDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GsimDetectorEventDataDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__GsimDetectorEventDataDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__GsimDetectorEventDataDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__GsimDetectorEventDataDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__GsimDetectorEventDataDictLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__GsimDetectorEventDataDictLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__GsimDetectorEventDataDictLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__GsimDetectorEventDataDictLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__GsimDetectorEventDataDictLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__GsimDetectorEventDataDictLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__GsimDetectorEventDataDictLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__GsimDetectorEventDataDictLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__GsimDetectorEventDataDictLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__GsimDetectorEventDataDictLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__GsimDetectorEventDataDictLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__GsimDetectorEventDataDictLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__GsimDetectorEventDataDictLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__GsimDetectorEventDataDictLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__GsimDetectorEventDataDictLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__GsimDetectorEventDataDictLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__GsimDetectorEventDataDictLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__GsimDetectorEventDataDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__GsimDetectorEventDataDictLN_GsimDetectorEventData.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableGsimDetectorEventDataDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__GsimDetectorEventDataDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__GsimDetectorEventDataDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__GsimDetectorEventDataDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__GsimDetectorEventDataDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__GsimDetectorEventDataDictLN_string);
   G__get_linked_tagnum_fwd(&G__GsimDetectorEventDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__GsimDetectorEventDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__GsimDetectorEventDataDictLN_TClonesArray);
   G__get_linked_tagnum_fwd(&G__GsimDetectorEventDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__GsimDetectorEventDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__GsimDetectorEventDataDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__GsimDetectorEventDataDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__GsimDetectorEventDataDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GsimDetectorEventDataDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__GsimDetectorEventDataDictLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GsimDetectorEventDataDictLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GsimDetectorEventDataDictLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GsimDetectorEventDataDictLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GsimDetectorEventDataDictLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GsimDetectorEventDataDictLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GsimDetectorEventDataDictLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GsimDetectorEventDataDictLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GsimDetectorEventDataDictLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GsimDetectorEventDataDictLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GsimDetectorEventDataDictLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GsimDetectorEventDataDictLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GsimDetectorEventDataDictLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__GsimDetectorEventDataDictLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GsimDetectorEventDataDictLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__GsimDetectorEventDataDictLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GsimDetectorEventDataDictLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__GsimDetectorEventDataDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__GsimDetectorEventDataDictLN_GsimDetectorEventData),sizeof(GsimDetectorEventData),-1,292096,(char*)NULL,G__setup_memvarGsimDetectorEventData,G__setup_memfuncGsimDetectorEventData);
}
extern "C" void G__cpp_setupGsimDetectorEventDataDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupGsimDetectorEventDataDict()");
  G__set_cpp_environmentGsimDetectorEventDataDict();
  G__cpp_setup_tagtableGsimDetectorEventDataDict();

  G__cpp_setup_inheritanceGsimDetectorEventDataDict();

  G__cpp_setup_typetableGsimDetectorEventDataDict();

  G__cpp_setup_memvarGsimDetectorEventDataDict();

  G__cpp_setup_memfuncGsimDetectorEventDataDict();
  G__cpp_setup_globalGsimDetectorEventDataDict();
  G__cpp_setup_funcGsimDetectorEventDataDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncGsimDetectorEventDataDict();
  return;
}
class G__cpp_setup_initGsimDetectorEventDataDict {
  public:
    G__cpp_setup_initGsimDetectorEventDataDict() { G__add_setup_func("GsimDetectorEventDataDict",(G__incsetup)(&G__cpp_setupGsimDetectorEventDataDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initGsimDetectorEventDataDict() { G__remove_setup_func("GsimDetectorEventDataDict"); }
};
G__cpp_setup_initGsimDetectorEventDataDict G__cpp_setup_initializerGsimDetectorEventDataDict;

