//
// File generated by rootcint at Sun Jun  3 02:38:15 2012

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME srcdIGsimProcessDataDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "GsimProcessDataDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void GsimProcessData_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_GsimProcessData(void *p = 0);
   static void *newArray_GsimProcessData(Long_t size, void *p);
   static void delete_GsimProcessData(void *p);
   static void deleteArray_GsimProcessData(void *p);
   static void destruct_GsimProcessData(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::GsimProcessData*)
   {
      ::GsimProcessData *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::GsimProcessData >(0);
      static ::ROOT::TGenericClassInfo 
         instance("GsimProcessData", ::GsimProcessData::Class_Version(), "././GsimData/GsimProcessData.h", 27,
                  typeid(::GsimProcessData), DefineBehavior(ptr, ptr),
                  &::GsimProcessData::Dictionary, isa_proxy, 4,
                  sizeof(::GsimProcessData) );
      instance.SetNew(&new_GsimProcessData);
      instance.SetNewArray(&newArray_GsimProcessData);
      instance.SetDelete(&delete_GsimProcessData);
      instance.SetDeleteArray(&deleteArray_GsimProcessData);
      instance.SetDestructor(&destruct_GsimProcessData);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::GsimProcessData*)
   {
      return GenerateInitInstanceLocal((::GsimProcessData*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::GsimProcessData*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *GsimProcessData::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *GsimProcessData::Class_Name()
{
   return "GsimProcessData";
}

//______________________________________________________________________________
const char *GsimProcessData::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::GsimProcessData*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int GsimProcessData::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::GsimProcessData*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void GsimProcessData::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::GsimProcessData*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *GsimProcessData::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::GsimProcessData*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void GsimProcessData::Streamer(TBuffer &R__b)
{
   // Stream an object of class GsimProcessData.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(GsimProcessData::Class(),this);
   } else {
      R__b.WriteClassBuffer(GsimProcessData::Class(),this);
   }
}

//______________________________________________________________________________
void GsimProcessData::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class GsimProcessData.
      TClass *R__cl = ::GsimProcessData::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "processID", &processID);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "processName", &processName);
      R__insp.InspectMember(processName, "processName.");
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_GsimProcessData(void *p) {
      return  p ? new(p) ::GsimProcessData : new ::GsimProcessData;
   }
   static void *newArray_GsimProcessData(Long_t nElements, void *p) {
      return p ? new(p) ::GsimProcessData[nElements] : new ::GsimProcessData[nElements];
   }
   // Wrapper around operator delete
   static void delete_GsimProcessData(void *p) {
      delete ((::GsimProcessData*)p);
   }
   static void deleteArray_GsimProcessData(void *p) {
      delete [] ((::GsimProcessData*)p);
   }
   static void destruct_GsimProcessData(void *p) {
      typedef ::GsimProcessData current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::GsimProcessData

/********************************************************
* src/GsimProcessDataDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableGsimProcessDataDict();

extern "C" void G__set_cpp_environmentGsimProcessDataDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("./GsimData/GsimProcessData.h");
  G__cpp_reset_tagtableGsimProcessDataDict();
}
#include <new>
extern "C" int G__cpp_dllrevGsimProcessDataDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* GsimProcessData */
static int G__GsimProcessDataDict_177_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   GsimProcessData* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new GsimProcessData[n];
     } else {
       p = new((void*) gvp) GsimProcessData[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new GsimProcessData;
     } else {
       p = new((void*) gvp) GsimProcessData;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__GsimProcessDataDictLN_GsimProcessData));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimProcessDataDict_177_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   GsimProcessData* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new GsimProcessData(*(GsimProcessData*) libp->para[0].ref);
   } else {
     p = new((void*) gvp) GsimProcessData(*(GsimProcessData*) libp->para[0].ref);
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__GsimProcessDataDictLN_GsimProcessData));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimProcessDataDict_177_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GsimProcessData*) G__getstructoffset())->initializeDataValues();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimProcessDataDict_177_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const GsimProcessData& obj = ((GsimProcessData*) G__getstructoffset())->operator=(*(GsimProcessData*) libp->para[0].ref);
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimProcessDataDict_177_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const GsimProcessData*) G__getstructoffset())->operator==(*(GsimProcessData*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimProcessDataDict_177_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const GsimProcessData*) G__getstructoffset())->operator!=(*(GsimProcessData*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimProcessDataDict_177_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) GsimProcessData::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimProcessDataDict_177_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) GsimProcessData::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimProcessDataDict_177_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) GsimProcessData::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimProcessDataDict_177_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      GsimProcessData::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimProcessDataDict_177_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GsimProcessData*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimProcessDataDict_177_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) GsimProcessData::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimProcessDataDict_177_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) GsimProcessData::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimProcessDataDict_177_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) GsimProcessData::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GsimProcessDataDict_177_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) GsimProcessData::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef GsimProcessData G__TGsimProcessData;
static int G__GsimProcessDataDict_177_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (GsimProcessData*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((GsimProcessData*) (soff+(sizeof(GsimProcessData)*i)))->~G__TGsimProcessData();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (GsimProcessData*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((GsimProcessData*) (soff))->~G__TGsimProcessData();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* GsimProcessData */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncGsimProcessDataDict {
 public:
  G__Sizep2memfuncGsimProcessDataDict(): p(&G__Sizep2memfuncGsimProcessDataDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncGsimProcessDataDict::*p)();
};

size_t G__get_sizep2memfuncGsimProcessDataDict()
{
  G__Sizep2memfuncGsimProcessDataDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceGsimProcessDataDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__GsimProcessDataDictLN_GsimProcessData))) {
     GsimProcessData *G__Lderived;
     G__Lderived=(GsimProcessData*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__GsimProcessDataDictLN_GsimProcessData),G__get_linked_tagnum(&G__GsimProcessDataDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableGsimProcessDataDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__GsimProcessDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GsimProcessDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GsimProcessDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GsimProcessDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GsimProcessDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__GsimProcessDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GsimProcessDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GsimProcessDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GsimProcessDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GsimProcessDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* GsimProcessData */
static void G__setup_memvarGsimProcessData(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__GsimProcessDataDictLN_GsimProcessData));
   { GsimProcessData *p; p=(GsimProcessData*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->processID)-(long)(p)),114,0,0,-1,G__defined_typename("UShort_t"),-1,1,"processID=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->processName)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__GsimProcessDataDictLN_TString),-1,-1,1,"processName=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GsimProcessDataDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarGsimProcessDataDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncGsimProcessData(void) {
   /* GsimProcessData */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__GsimProcessDataDictLN_GsimProcessData));
   G__memfunc_setup("GsimProcessData",1513,G__GsimProcessDataDict_177_0_1, 105, G__get_linked_tagnum(&G__GsimProcessDataDictLN_GsimProcessData), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GsimProcessData",1513,G__GsimProcessDataDict_177_0_2, 105, G__get_linked_tagnum(&G__GsimProcessDataDictLN_GsimProcessData), -1, 0, 1, 1, 1, 0, "u 'GsimProcessData' - 11 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Clear",487,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "C - 'Option_t' 10 '\"\"' opt", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("initializeDataValues",2076,G__GsimProcessDataDict_177_0_4, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator=",937,G__GsimProcessDataDict_177_0_5, 117, G__get_linked_tagnum(&G__GsimProcessDataDictLN_GsimProcessData), -1, 1, 1, 1, 1, 0, "u 'GsimProcessData' - 11 - right", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator==",998,G__GsimProcessDataDict_177_0_6, 103, -1, -1, 0, 1, 1, 1, 8, "u 'GsimProcessData' - 11 - right", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator!=",970,G__GsimProcessDataDict_177_0_7, 103, -1, -1, 0, 1, 1, 1, 8, "u 'GsimProcessData' - 11 - right", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__GsimProcessDataDict_177_0_8, 85, G__get_linked_tagnum(&G__GsimProcessDataDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&GsimProcessData::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__GsimProcessDataDict_177_0_9, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&GsimProcessData::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__GsimProcessDataDict_177_0_10, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&GsimProcessData::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__GsimProcessDataDict_177_0_11, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&GsimProcessData::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__GsimProcessDataDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - insp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__GsimProcessDataDict_177_0_15, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__GsimProcessDataDict_177_0_16, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&GsimProcessData::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__GsimProcessDataDict_177_0_17, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&GsimProcessData::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__GsimProcessDataDict_177_0_18, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&GsimProcessData::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__GsimProcessDataDict_177_0_19, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&GsimProcessData::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~GsimProcessData", 1639, G__GsimProcessDataDict_177_0_20, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncGsimProcessDataDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalGsimProcessDataDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcGsimProcessDataDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__GsimProcessDataDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__GsimProcessDataDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__GsimProcessDataDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__GsimProcessDataDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__GsimProcessDataDictLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__GsimProcessDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__GsimProcessDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__GsimProcessDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__GsimProcessDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__GsimProcessDataDictLN_GsimProcessData = { "GsimProcessData" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableGsimProcessDataDict() {
  G__GsimProcessDataDictLN_TClass.tagnum = -1 ;
  G__GsimProcessDataDictLN_TBuffer.tagnum = -1 ;
  G__GsimProcessDataDictLN_TMemberInspector.tagnum = -1 ;
  G__GsimProcessDataDictLN_TObject.tagnum = -1 ;
  G__GsimProcessDataDictLN_TString.tagnum = -1 ;
  G__GsimProcessDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__GsimProcessDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GsimProcessDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__GsimProcessDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GsimProcessDataDictLN_GsimProcessData.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableGsimProcessDataDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__GsimProcessDataDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__GsimProcessDataDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__GsimProcessDataDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__GsimProcessDataDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__GsimProcessDataDictLN_TString);
   G__get_linked_tagnum_fwd(&G__GsimProcessDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__GsimProcessDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__GsimProcessDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__GsimProcessDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__GsimProcessDataDictLN_GsimProcessData),sizeof(GsimProcessData),-1,294656,(char*)NULL,G__setup_memvarGsimProcessData,G__setup_memfuncGsimProcessData);
}
extern "C" void G__cpp_setupGsimProcessDataDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupGsimProcessDataDict()");
  G__set_cpp_environmentGsimProcessDataDict();
  G__cpp_setup_tagtableGsimProcessDataDict();

  G__cpp_setup_inheritanceGsimProcessDataDict();

  G__cpp_setup_typetableGsimProcessDataDict();

  G__cpp_setup_memvarGsimProcessDataDict();

  G__cpp_setup_memfuncGsimProcessDataDict();
  G__cpp_setup_globalGsimProcessDataDict();
  G__cpp_setup_funcGsimProcessDataDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncGsimProcessDataDict();
  return;
}
class G__cpp_setup_initGsimProcessDataDict {
  public:
    G__cpp_setup_initGsimProcessDataDict() { G__add_setup_func("GsimProcessDataDict",(G__incsetup)(&G__cpp_setupGsimProcessDataDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initGsimProcessDataDict() { G__remove_setup_func("GsimProcessDataDict"); }
};
G__cpp_setup_initGsimProcessDataDict G__cpp_setup_initializerGsimProcessDataDict;

