/********************************************************************
* src/GsimDetectorHitDataDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/GsimDetectorHitDataDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableGsimDetectorHitDataDict();
extern void G__cpp_setup_inheritanceGsimDetectorHitDataDict();
extern void G__cpp_setup_typetableGsimDetectorHitDataDict();
extern void G__cpp_setup_memvarGsimDetectorHitDataDict();
extern void G__cpp_setup_globalGsimDetectorHitDataDict();
extern void G__cpp_setup_memfuncGsimDetectorHitDataDict();
extern void G__cpp_setup_funcGsimDetectorHitDataDict();
extern void G__set_cpp_environmentGsimDetectorHitDataDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "./GsimData/GsimDetectorHitData.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__GsimDetectorHitDataDictLN_TClass;
extern G__linked_taginfo G__GsimDetectorHitDataDictLN_TBuffer;
extern G__linked_taginfo G__GsimDetectorHitDataDictLN_TMemberInspector;
extern G__linked_taginfo G__GsimDetectorHitDataDictLN_TObject;
extern G__linked_taginfo G__GsimDetectorHitDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__GsimDetectorHitDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GsimDetectorHitDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__GsimDetectorHitDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GsimDetectorHitDataDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__GsimDetectorHitDataDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__GsimDetectorHitDataDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__GsimDetectorHitDataDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__GsimDetectorHitDataDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__GsimDetectorHitDataDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__GsimDetectorHitDataDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__GsimDetectorHitDataDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__GsimDetectorHitDataDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__GsimDetectorHitDataDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__GsimDetectorHitDataDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__GsimDetectorHitDataDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__GsimDetectorHitDataDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__GsimDetectorHitDataDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__GsimDetectorHitDataDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__GsimDetectorHitDataDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__GsimDetectorHitDataDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__GsimDetectorHitDataDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__GsimDetectorHitDataDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__GsimDetectorHitDataDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__GsimDetectorHitDataDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__GsimDetectorHitDataDictLN_TVector3;
extern G__linked_taginfo G__GsimDetectorHitDataDictLN_GsimDetectorHitData;

/* STUB derived class for protected member access */
