/********************************************************************
* src/GsimTrackDataDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/GsimTrackDataDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableGsimTrackDataDict();
extern void G__cpp_setup_inheritanceGsimTrackDataDict();
extern void G__cpp_setup_typetableGsimTrackDataDict();
extern void G__cpp_setup_memvarGsimTrackDataDict();
extern void G__cpp_setup_globalGsimTrackDataDict();
extern void G__cpp_setup_memfuncGsimTrackDataDict();
extern void G__cpp_setup_funcGsimTrackDataDict();
extern void G__set_cpp_environmentGsimTrackDataDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "./GsimData/GsimTrackData.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__GsimTrackDataDictLN_TClass;
extern G__linked_taginfo G__GsimTrackDataDictLN_TBuffer;
extern G__linked_taginfo G__GsimTrackDataDictLN_TMemberInspector;
extern G__linked_taginfo G__GsimTrackDataDictLN_TObject;
extern G__linked_taginfo G__GsimTrackDataDictLN_string;
extern G__linked_taginfo G__GsimTrackDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__GsimTrackDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GsimTrackDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__GsimTrackDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GsimTrackDataDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__GsimTrackDataDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__GsimTrackDataDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__GsimTrackDataDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__GsimTrackDataDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__GsimTrackDataDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__GsimTrackDataDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__GsimTrackDataDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__GsimTrackDataDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__GsimTrackDataDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__GsimTrackDataDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__GsimTrackDataDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__GsimTrackDataDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__GsimTrackDataDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__GsimTrackDataDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__GsimTrackDataDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__GsimTrackDataDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__GsimTrackDataDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__GsimTrackDataDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__GsimTrackDataDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__GsimTrackDataDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__GsimTrackDataDictLN_TVector3;
extern G__linked_taginfo G__GsimTrackDataDictLN_listlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__GsimTrackDataDictLN_GsimTrackData;

/* STUB derived class for protected member access */
