/********************************************************************
* src/GsimDigiDataDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/GsimDigiDataDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableGsimDigiDataDict();
extern void G__cpp_setup_inheritanceGsimDigiDataDict();
extern void G__cpp_setup_typetableGsimDigiDataDict();
extern void G__cpp_setup_memvarGsimDigiDataDict();
extern void G__cpp_setup_globalGsimDigiDataDict();
extern void G__cpp_setup_memfuncGsimDigiDataDict();
extern void G__cpp_setup_funcGsimDigiDataDict();
extern void G__set_cpp_environmentGsimDigiDataDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "./GsimData/GsimDigiData.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__GsimDigiDataDictLN_TClass;
extern G__linked_taginfo G__GsimDigiDataDictLN_TBuffer;
extern G__linked_taginfo G__GsimDigiDataDictLN_TMemberInspector;
extern G__linked_taginfo G__GsimDigiDataDictLN_TObject;
extern G__linked_taginfo G__GsimDigiDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__GsimDigiDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GsimDigiDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__GsimDigiDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GsimDigiDataDictLN_GsimDigiData;

/* STUB derived class for protected member access */
