/********************************************************************
* src/GsimPhysicalVolumeDataDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/GsimPhysicalVolumeDataDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableGsimPhysicalVolumeDataDict();
extern void G__cpp_setup_inheritanceGsimPhysicalVolumeDataDict();
extern void G__cpp_setup_typetableGsimPhysicalVolumeDataDict();
extern void G__cpp_setup_memvarGsimPhysicalVolumeDataDict();
extern void G__cpp_setup_globalGsimPhysicalVolumeDataDict();
extern void G__cpp_setup_memfuncGsimPhysicalVolumeDataDict();
extern void G__cpp_setup_funcGsimPhysicalVolumeDataDict();
extern void G__set_cpp_environmentGsimPhysicalVolumeDataDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "./GsimData/GsimPhysicalVolumeData.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__GsimPhysicalVolumeDataDictLN_TClass;
extern G__linked_taginfo G__GsimPhysicalVolumeDataDictLN_TBuffer;
extern G__linked_taginfo G__GsimPhysicalVolumeDataDictLN_TMemberInspector;
extern G__linked_taginfo G__GsimPhysicalVolumeDataDictLN_TObject;
extern G__linked_taginfo G__GsimPhysicalVolumeDataDictLN_TString;
extern G__linked_taginfo G__GsimPhysicalVolumeDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__GsimPhysicalVolumeDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GsimPhysicalVolumeDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__GsimPhysicalVolumeDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GsimPhysicalVolumeDataDictLN_GsimPhysicalVolumeData;

/* STUB derived class for protected member access */
