/********************************************************************
* src/GsimDetectorEventDataDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/GsimDetectorEventDataDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableGsimDetectorEventDataDict();
extern void G__cpp_setup_inheritanceGsimDetectorEventDataDict();
extern void G__cpp_setup_typetableGsimDetectorEventDataDict();
extern void G__cpp_setup_memvarGsimDetectorEventDataDict();
extern void G__cpp_setup_globalGsimDetectorEventDataDict();
extern void G__cpp_setup_memfuncGsimDetectorEventDataDict();
extern void G__cpp_setup_funcGsimDetectorEventDataDict();
extern void G__set_cpp_environmentGsimDetectorEventDataDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "./GsimData/GsimDetectorEventData.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__GsimDetectorEventDataDictLN_TClass;
extern G__linked_taginfo G__GsimDetectorEventDataDictLN_TBuffer;
extern G__linked_taginfo G__GsimDetectorEventDataDictLN_TMemberInspector;
extern G__linked_taginfo G__GsimDetectorEventDataDictLN_TObject;
extern G__linked_taginfo G__GsimDetectorEventDataDictLN_string;
extern G__linked_taginfo G__GsimDetectorEventDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__GsimDetectorEventDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GsimDetectorEventDataDictLN_TClonesArray;
extern G__linked_taginfo G__GsimDetectorEventDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__GsimDetectorEventDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GsimDetectorEventDataDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__GsimDetectorEventDataDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__GsimDetectorEventDataDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__GsimDetectorEventDataDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__GsimDetectorEventDataDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__GsimDetectorEventDataDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__GsimDetectorEventDataDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__GsimDetectorEventDataDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__GsimDetectorEventDataDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__GsimDetectorEventDataDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__GsimDetectorEventDataDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__GsimDetectorEventDataDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__GsimDetectorEventDataDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__GsimDetectorEventDataDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__GsimDetectorEventDataDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__GsimDetectorEventDataDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__GsimDetectorEventDataDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__GsimDetectorEventDataDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__GsimDetectorEventDataDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__GsimDetectorEventDataDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__GsimDetectorEventDataDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__GsimDetectorEventDataDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__GsimDetectorEventDataDictLN_GsimDetectorEventData;

/* STUB derived class for protected member access */
