/GsimPhysicsListFactory/QGSP_BERT/buildAndRegister
/GsimPrimaryGeneratorActionFactory/GsimGeneralParticleSource/buildAndRegister gps
/gps/particle KLpi0pi0
/gps/energy 1 GeV
/gps/position 0 0 -1 m
/gps/direction 0 0 1
/control/execute oglsini.mac
/GsimEventAction/setVisualizationMode 1
#/GsimEventAction/setAccumulationNumber -1
#/GsimTrackingAction/setBriefTrackStore true

/GsimDetector/world/setParameters 5*m 5*m 60*m
/GsimDetector/world/setOuterVisibility 0
/GsimDetector/world/setOuterMaterial G4_Galactic
/GsimDetectorFactory/GsimE14/buildAndRegister e14 /world 1
/GsimDetectorManager/update
/run/initialize
/run/beamOn 1
