/GsimPhysicsListFactory/QGSP_BERT/buildAndRegister
/GsimPrimaryGeneratorActionFactory/GsimGeneralParticleSource/buildAndRegister gps
/gps/particle pi+
/gps/energy 1 GeV
/gps/direction 0 0 1
#/run/verbose 2
#/event/verbose 10
#/tracking/verbose 10
/control/execute oglini.mac
/GsimEventAction/setVisualizationMode 1
#/GsimEventAction/setAccumulationNumber -1
/GsimTrackingAction/setBriefTrackStore true


/GsimDetector/world/setParameters 10*cm 10*cm 10*cm
/GsimDetectorFactory/GsimBox/buildAndRegister box /world
/GsimDetector/world/box/setOuterMaterial G4_Fe
/GsimDetector/world/box/setTranslationVector 0 0 2.5*cm
/GsimDetector/world/box/setSensitiveDetectorWithName box
/GsimDetectorManager/update
/run/initialize
/run/beamOn 2
