/GsimPhysicsListFactory/QGSP_BERT_HP/buildAndRegister 
/GsimPrimaryGeneratorActionFactory/GsimGeneralParticleSource/buildAndRegister gps
/gps/particle pi+
/gps/energy 1 GeV
/gps/direction 0 0 1
#/run/verbose 2
#/event/verbose 10
#/tracking/verbose 10
/control/execute oglini.mac
/GsimEventAction/setVisualizationMode 1
#/GsimEventAction/setAccumulationNumber -1
/GsimTrackingAction/setBriefTrackStore true


/GsimDetectorFactory/GsimBox/buildAndRegister box /world
/GsimDetector/world/box/setOuterMaterial G4_Na
/GsimDetectorManager/update

/run/initialize
/run/beamOn 100

/GsimDetector/world/box/setOuterMaterial G4_Cu
/GsimDetectorFactory/GsimBox/buildAndRegister box2 /world 0 0 1*m
/GsimDetector/world/box2/setOuterMaterial G4_Pb
/GsimDetectorManager/update

/run/beamOn 100

