/GsimPhysicsListFactory/QGSP_BERT/buildAndRegister
/GsimPrimaryGeneratorActionFactory/GsimGeneralParticleSource/buildAndRegister gps
/gps/particle pi+
/gps/energy 1 GeV
/gps/direction 0 0 1
#/run/verbose 2
#/event/verbose 10
#/tracking/verbose 10
/control/execute oglini.mac
/GsimEventAction/setVisualizationMode 1
#/GsimEventAction/setAccumulationNumber -1
/GsimTrackingAction/setBriefTrackStore true


/GsimDetectorFactory/GsimBox/buildAndRegister box /world
/GsimDetector/world/box/setOuterMaterial G4_Fe
/GsimDetector/world/box/setSensitiveDetectorWithName box 0
/GsimDetectorManager/update
/run/initialize
/run/beamOn 1
/GsimDetector/world/box/setOuterMaterial G4_Cu
/GsimDetectorFactory/GsimBox/buildAndRegister box2 /world 0 0 1*m
/GsimDetector/world/box2/setOuterMaterial G4_Pb
/GsimDetector/world/box2/setSensitiveDetectorWithName box 1
/GsimDetectorManager/update
/run/beamOn 10
