/GsimPhysicsListFactory/QGSP_BERT/buildAndRegister
/GsimPrimaryGeneratorActionFactory/GsimGeneralParticleSource/buildAndRegister gps

/gps/position 0 0 -33.001 mm
/gps/ang/type beam2d
/gps/ang/sigma_x 0.001 rad
/gps/ang/sigma_y 0.0023 rad
/gps/ang/rot1 -1 0 0
/gps/ang/rot2 0 1 0
/gps/pos/type Beam
/gps/pos/sigma_x 1.3 mm
/gps/pos/sigma_y 1.3 mm
/gps/particle proton
/gps/energy 30. GeV


#/control/execute oglsini.mac
#/GsimEventAction/setVisualizationMode 1

/control/execute e14target.mac

/GsimDetector/world/det1/setSensitiveDetectorWithName det1
/GsimDetector/world/det1/setFastSimulationLevel 5
/GsimDetector/world/det1/setHitsStore true
/GsimDetector/world/det1/setDigiStore false

/GsimTrackingAction/setBriefTrackStore false
/GsimTrackingAction/setForceStorePrimary false

/GsimDetectorManager/update
/run/initialize
